services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: note-app-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    restart: unless-stopped


  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: note-app-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    restart: unless-stopped
